### PR TITLE
Sum QoL Features

### PR DESCRIPTION
**Pull request by Knastoron**
- Automated Usage for integration in horrifying AutoHotKey scripts :^}
- automatically creates grid, if all 4 .txt files exist in the parent folder / in the submitted folder
- now takes command line arguments! (target path for exported files (and .txt files); 1 Argument for both (may change in the future idk

### CODE REVIEW

**Comment by KtRNofficial** [comment]
Pis of

**Comment by KtRNofficial** [comment]
now takes command line arguments! (target path for exported files (and .txt files); 1 Argument for both (may change in the future idk
=> Feeling cute, might not change this at all idk

**Comment by Knastoron** [comment]
u know what, fk u *uncalculates your arcgis calculations*

**Comment by KtRNofficial** [comment]
oh no it's all falling apart! Abandon Mepp

**Pull request merged**
